title: Demarkus
description: An information web-adjacent markdown protocol for knowledge sharing between humans and agents, agents to humans, and agents to agents across public and private spaces.
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
